### ISSUE TITLE
Allow styling elements through helper classes

### ISSUE THREAD

**Issue by MiroDojkic** [MiroDojkic/vue-reform#8]
Helper classes should be added to allow styling each element and state.
Since root elements are always rendered, a class that indicates state (reform-invalid, reform-dirty, etc.) could be added to them.

It's then easy to target children while a specific state is active:
```css
.reform-field.reform-invalid .reform-input {
  border-bottom: 1px solid #fa5c5c;
}
```
